[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x", "openssl", "libnss3", "libatk1.0-0", "libatk-bridge2.0-0", "libcups2", "libgbm1", "libasound2t64", "libpangocairo-1.0-0", "libxss1", "libgtk-3-0", "libxshmfence1", "libglu1", "chromium"]

[phases.install]
cmds = ["cd hangouts-3.0 && npm ci --omit=dev"]

[phases.build]
cmds = [
  "cd hangouts-3.0 && npx prisma generate --schema=./prisma/schema.prisma",
  "cd hangouts-3.0 && NODE_ENV=production npm run build"
]

[start]
cmd = "cd hangouts-3.0 && npm start"
