[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x", "openssl"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "cd hangouts-3.0 && npm install",
  "cd hangouts-3.0 && npx prisma generate",
  "cd hangouts-3.0 && npm run build:production"
]

[start]
cmd = "cd hangouts-3.0 && npm start"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
